### ISSUE TITLE
You can use `FROM janx/ubuntu-dev` instead of `FROM ubuntu:16.04`

### ISSUE THREAD

**Issue by jankeromnes** [Mte90/wordpress-janitor#1]
Nice job! 😄

Please note, you can derive this Dockerfile `FROM janx/ubuntu-dev` instead of `FROM ubuntu:16.04`, because `ubuntu-dev` already has [a lot of useful developers tools pre-installed](https://github.com/JanitorTechnology/dockerfiles/blob/master/ubuntu-dev/ubuntu-dev.dockerfile), including very recent Git, Node.js, and many others.

Plus it also pre-installs Cloud9 IDE and noVNC, which you don't want to install yourself here.

**Comment by Mte90** [comment]
Already updated, I forgotten to commit :-)
